 const initialPlaces = [
  {
    "name": "Pelicano Coffee co.",
    "pictures": "https://dl.airtable.com/.attachments/e07a40279808eea2c1ccb9569e492348/a6bf2118/dcb19a_42728ce26dbf4fdb87db50d9820d2c60mv2.webp",
    "category": "Coffee & Drinks",
    "cost": "££",
    "recommend": "true",
    "do_boxes": "",
    "has_online_shop": "",
    "type_delivery": "Home Delivery",
    "notes": "One of favourite coffeeshop and roster in Brighton.",
    "how_to_order": "Online Shop on their Website",
    "website": "https://www.pelicanocoffee.com/",
    "voucher": "Use the code - isolationcoffee for 20% off all orders"
  },
  {
    "name": "Brighton Express Meats",
    "pictures": "https://dl.airtable.com/.attachments/867815f0cdfd0fdbd0a27d4b33d59b13/f03cb86f/71589a_87b4cea5ad2547da87354553783125c1mv2.webp",
    "category": "Butcher",
    "cost": "£-££",
    "recommend": "true",
    "do_boxes": "true",
    "has_online_shop": "true",
    "type_delivery": "Home Delivery,Collection",
    "notes": "Brighton Express Meats specialise in the home delivery of high quality, locally sourced meat produce directly to customers doors in Brighton & Hove, and the surrounding area.\n\n​\n\nWe offer a free next day delivery service for orders placed up until 4pm, for delivery Monday to Saturday. Orders can be placed online or over the phone. Our friendly staff will be on hand to take your order and confirm details of your delivery and can be paid for easily over the phone using a credit or debit card.\n\n​\n\nOur products are carefully sourced from UK sources where possible and trusted EU suppliers.\n\n​\n\nTo make your life easier we have put together some simple weekly meat packs at competitive pricing.",
    "how_to_order": "Online Shop on their Website",
    "website": "https://www.brightonexpressmeats.co.uk/",
    "voucher": ""
  },
  {
    "name": "Brighton Magazine",
    "pictures": "https://dl.airtable.com/.attachments/b06f290ff14160c7f82360c92ca854c9/d2e30107/10808792_1501692666765335_504167949_a.jpg",
    "category": "Culture",
    "cost": "£-££",
    "recommend": "true",
    "do_boxes": "",
    "has_online_shop": "",
    "type_delivery": "Home Delivery",
    "notes": "Brighton Magazine is probably one of my favourite shops in Brighton. Offering a wide range of independent Magazines and other Publications from all over the world, is one of this places that I like to go once in while and get lost in their shelves. \n\nThey do Online Shopping as well.",
    "how_to_order": "Online Shop on their Website",
    "website": "https://www.magazinebrighton.com/",
    "voucher": ""
  },
  {
    "name": "Spring Gardens Nursery",
    "pictures": "https://dl.airtable.com/.attachments/8f6a84e6f7c1111be0cd35072d88e942/fb69e00c/Screenshot2020-04-05at21_32_37.png",
    "category": "Groceries,Fruits & Veggies",
    "cost": "£-££",
    "recommend": "",
    "do_boxes": "true",
    "has_online_shop": "",
    "type_delivery": "Home Delivery,Collection",
    "notes": "Spring Gardens Nursery specialises in 'Pick Your Own' fruit and vegetables and is a great day out for all the family. You will find us just off the A24, located at the bottom of the South Downs in the beautiful country side of West Sussex. We have 35 acres of fields and orchards to walk around, providing you with a wide variety of seasonal produce.",
    "how_to_order": "Delivery will be within THREE days of ordering. Please send your order by EMAIL to\n(springgardenspyo@outlook.com);\n• Name\n• Address including post code\n• Phone number\nPlease wait for confirmation before expecting delivery. \n\nMinimum order £25 for home delivery.",
    "website": "https://springgardensnursery.uk/",
    "voucher": ""
  },
  {
    "name": "Chef's Farms",
    "pictures": "https://dl.airtable.com/.attachments/7b0fbbc98598eb10494e0869997a3a56/c93e60c3/51125102_378527029592286_5464977165512605696_n.jpg",
    "category": "Fruits & Veggies,Groceries,Coffee & Drinks",
    "cost": "££-£££",
    "recommend": "",
    "do_boxes": "true",
    "has_online_shop": "",
    "type_delivery": "Home Delivery",
    "notes": "the chefs farms accreditation ensures that our farmers us sustainable farming techniques whilst matching consumer demand. by supporting our experienced food producers with our access to a knowledgeable and experienced market of chefs, we are promoting our overall product quality.\nwe believe that ethically and sustainably produced food is the future of good quality food in the uk.",
    "how_to_order": "Online Shop on their Website",
    "website": "https://www.chefsfarms.co.uk/",
    "voucher": ""
  },
  {
    "name": "Brighton Fish Sales",
    "pictures": "https://dl.airtable.com/.attachments/4fd59ee100b3de61d35fe7f568a9f2c4/01581daa/DSC_5410-e1581774605819.jpg",
    "category": "Fish Market",
    "cost": "£-££",
    "recommend": "",
    "do_boxes": "",
    "has_online_shop": "",
    "type_delivery": "Collection,Home Delivery",
    "notes": "Our shop “FISH” is a great local retail experience.\n\nWe have just undergone a major refurbishment as we hit our 10 year anniversary since opening. We have also made some great changes which include, “ready to eat” and “Ready to cook” products on the counter.\n\nWe have also made a conscious decision as a company in minimise plastic packaging. We want to encourage our customers to bring their own bags or Tupperware boxes and be rewarded with a loyalty card which we get stamped each time bring in your own packaging. Paper bags and “bags for life” will be available to purchase over the counter at a small cost.\n\nThe shop by Hove Lagoon offers the widest selection of local fish and shellfish caught by our fleet of boats. We also stock seafood from further afield in order to offer our customers the best possible choice of seafood.\n\nFrom fresh fish to live shellfish, frozen and complimentary products, our skilled and knowledgeable team can assist you with the purchase and preparation of your seafood requirements.",
    "how_to_order": "Fresh fish and shellfish direct from our boats. Wholesale supplier plus on-site shop (8am-4pm Mon-Sat). Call 01273 414707 for home delivery.",
    "website": "https://www.brighton-fish-sales.co.uk/brighton-and-newhaven-fish-sales-shop-2/",
    "voucher": ""
  },
  {
    "name": "The Cheese Hut",
    "pictures": "https://dl.airtable.com/.attachments/301d89d45da3cd1b7817ac7b0e447f48/39c85f95/29417045_159458348097088_4162021398010658816_n.jpg",
    "category": "Cheese & Charcuterie",
    "cost": "££",
    "recommend": "",
    "do_boxes": "true",
    "has_online_shop": "",
    "type_delivery": "Home Delivery,Collection",
    "notes": "A local independent cheese retailer based in Hove, next to Hove Lagoon, specialising in Sussex Cheeses. British & Continental Cheeses also available.\n\nCatalog: https://cb07d425-7154-46fa-b7da-d36c2baf4c99.filesusr.com/ugd/e2afc4_336da4b7e1304aed934a38bd8a63a8d0.pdf",
    "how_to_order": "Call on 01273 789107 or email orders@thecheesehut.co.uk \n\nFree Delivery for orders over £25 to all of Sussex",
    "website": "https://www.thecheesehut.co.uk/",
    "voucher": "10% off for all NHS Workers"
  },
  {
    "name": "The Fruit Shop",
    "pictures": "https://dl.airtable.com/.attachments/944fd5fee3de04909235101d5c474e93/bbbe4dd9/Screenshot2020-04-05at21_55_56.png",
    "category": "Fruits & Veggies",
    "cost": "£",
    "recommend": "true",
    "do_boxes": "",
    "has_online_shop": "",
    "type_delivery": "Home Delivery,Collection",
    "notes": "A local independent shop at the Open Market.\n\n🍇/ / Family run business\n🍎/ / Fresh produce, great prices\n🥕/ / Brighton Open Market\n🥝/ / Open Monday-Saturday 8am-5pm\n🍌/ / Bananas about fruit & veg",
    "how_to_order": "To place your order for delivery please DM on Instagram us your order and we will get back to you with a price & payment details, once you place your order we will deliver the following day on a FIRST COME FIRST SERVED basis! (available on all orders over £25!) We are also offering zero contact deliveries.",
    "website": "https://www.instagram.com/thefruitshopbrighton/",
    "voucher": ""
  },
  {
    "name": "Infinity Foods",
    "pictures": "https://dl.airtable.com/.attachments/6856e6a250da466559c6c1527ae3de67/1bb8d51e/43568462_256710335042843_1387356204195381248_n.jpg",
    "category": "Groceries",
    "cost": "££-£££",
    "recommend": "true",
    "do_boxes": "true",
    "has_online_shop": "",
    "type_delivery": "Home Delivery,Collection",
    "notes": "Set in the heart of Brighton’s North Laine, Infinity Foods Shop has one of the largest selection of organic and natural vegetarian and vegan foods in the South East. We also cater for a range of dietary needs, including gluten-free and raw food.",
    "how_to_order": "Online Shop on their Website",
    "website": "https://infinityfoodsretail.coop",
    "voucher": ""
  },
  {
    "name": "Laine Brew Co.",
    "pictures": "https://dl.airtable.com/.attachments/964d36daf677fe84ce04e0be92284233/b9b41dc6/laine-logo-colour.png",
    "category": "Coffee & Drinks",
    "cost": "££",
    "recommend": "true",
    "do_boxes": "true",
    "has_online_shop": "true",
    "type_delivery": "Home Delivery",
    "notes": "Born from the inspirational pub and beer scene of Brighton, Laine Brew Co brews beer imbued with a love of flavour, experimentation and good times. Our beers are unfiltered, unpasteurised and uncompromising – meaning more flavour and more love. \n\nOur beers are sold across our home town of Brighton and in a wide selection of nationwide outlets.",
    "how_to_order": "Online Shop on their Website",
    "website": "https://laine.shop",
    "voucher": ""
  },
  {
    "name": "UnBarred Brewery",
    "pictures": "https://dl.airtable.com/.attachments/73b19d59dfb81c6c21d1f79104b9c9dd/b812921a/66675879_466514614080971_3264560476540895232_n.jpg",
    "category": "Coffee & Drinks",
    "cost": "££",
    "recommend": "true",
    "do_boxes": "true",
    "has_online_shop": "true",
    "type_delivery": "Home Delivery",
    "notes": "No rules brewing from the heart of Brighton. Brewery + Taproom. Flavour without compromise, challenging convention with passion and care. Drink beer, have fun, enjoy in good company.",
    "how_to_order": "Online Shop on their Website",
    "website": "https://shop.unbarredbrewery.com",
    "voucher": "10% off all orders use BEUNBARRED at checkout"
  },
  {
    "name": "Bison Beer",
    "pictures": "https://dl.airtable.com/.attachments/30d2bf0e61e6dd68307701f04707892f/b4bb095a/67512661_394015434849875_4756417572964925440_n.jpg",
    "category": "Coffee & Drinks",
    "cost": "££",
    "recommend": "true",
    "do_boxes": "true",
    "has_online_shop": "true",
    "type_delivery": "Home Delivery",
    "notes": "Welcome to Bison Beer. We're a bar, bottleshop and brewery brand based in Brighton and Hove, actually. We stock a huge range of craft beer from around the world with a keen interest in the Sussex beer scene. We are local, independent and proud to be a part of what we think is the best city in the country.",
    "how_to_order": "Online Shop on their Website",
    "website": "bisonbeer.myshopify.com",
    "voucher": ""
  },
  {
    "name": "Resident Music",
    "pictures": "https://dl.airtable.com/.attachments/62c7827f274f7691c0ef1d2a93101103/da0784ec/64503409_705834329836918_7828653919411634176_n.jpg",
    "category": "Culture",
    "cost": "£-££",
    "recommend": "true",
    "do_boxes": "",
    "has_online_shop": "true",
    "type_delivery": "",
    "notes": "A truly independent record shop in the heart of the North Laine.\n\nAn unpretentious place of warmth, chat, humility, laughter, discovery and ultimately, sweet sweet music. music for all ears, from all eras. no genre or generation boundaries. no judgements. just enjoyment of everything that the culture of music and those that embrace it bring when they come together in a record shop environment.",
    "how_to_order": "Online Shop on their Website",
    "website": "http://www.resident-music.com",
    "voucher": ""
  }
]

export {initialPlaces};